Language strings reworked
dnGrep/dnGrep pull request #593
Opened 2021-12-01 16:55 UTC by comradekingu

I skipped all the strings I couldn't make sense of for now.
Pretty sure "resulting" is in error here and there.

2021-12-02 00:32 UTC, doug24 commented
You have a lot of good suggestions, and some that I don't agree with such as the addition of hyphens.  Before I go through all the changes, can we agree to use a style guide? I’d suggest the [Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/).  It addresses many of these issues.

2021-12-02 00:53 UTC, comradekingu commented
@doug24 My brain melted down with the hyphens. Some of them are warranted, and I figured too many was not the problem at hand. That style guide uses two styles of em dashes on the front page. I'll take any good arguments to fix things. I have not re-read it yet.
The problem isn't so much adhering to style, but rather to improve clarity.

2021-12-04 20:41 UTC, doug24 requested changes
I am not going to address every single change, but these comments apply to multiple changes:
I agree we should to use "dnGrep" everywhere.
I agree we should use sentence-style capitalization ([reference](https://docs.microsoft.com/en-us/style-guide/capitalization)).  I have always used title-style capitalization in table headers, but that isn't correct ([reference](https://docs.microsoft.com/en-us/style-guide/scannable-content/tables)).
In general, I'm going to say no to all the added hyphens, I don't think this is correct usage ([reference](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens)).  However, there are be some specific exceptions where you are correct.
"Filename" should be two words: [reference](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/f/file-name).  Same for "File size" and "File type".
"Plaintext" should be two words: [reference](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/plaintext-plain-text).
"Multiline" is the correct spelling, not "Multi-line": [reference](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/m/multi)
I'm going to go with US spelling, so "canceled" not "cancelled" [reference](https://docs.microsoft.com/en-us/style-guide/word-choice/use-us-spelling-avoid-non-english-words). If someone wants to create an en-GB resource, they can used British spelling.

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Show resulting lines in context</value>
No, not 'resulting'

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Show all matches</value>
The distinction is not if all matches are to be shown, but how much detail is shown about the matches.  Yes, 'verbose' is a programmer term.  Maybe:  "Show additional details about the matches found"?

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Run dnGrep as administrator to replace all of them.</value>
This doesn't make any sense to me.  Most options can be changed under any user account, but this one option requires the application to be run under an Administrator account.

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Change language?</value>
This label was my attempt to provide users with a link telling them how they could contribute a new translation for dnGrep.  To me, "Change language?" implies an action that takes effect immediately.  Now I'm thinking the label and link should just be deleted, and if someone is really interested they can find the information they need on github.

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <comment>Replace window, filename progress line: {0} is the index of the current file; {1} is the total number of files; {2} is the name of the current file; {3} is the number of matches found in
This extra space was add intentionally to improve readability.  But sure, it can be removed.

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Exclusion pattern:</value>
On the main window, the labels "Patterns to match" and "Patterns to exclude" are used.  We should be more consistent when referring to them.  So I think "Patterns to exclude:" or "Patterns excluded:" would be better here.

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Using \"Everything index\" search</value>
I really dislike the name "Everything" for an application, but I have no choice.  It is difficult to refer to it by name.  I think this should be "Using \"Everything\" index search"

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Restore Downwards</value>
No, "Restore Down" is a specific term used on the tooltip for the maximize button on the Windows application header - try it on any maximized window. The only reason it appears in the dnGrep application strings is that dnGrep uses a customized window frame for light and dark themes.

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>dnGgrep</value>
Hmm, a typo?

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Everything index Service</value>
Everything index service

2021-12-04 20:41 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>    </resheader>
I am not going to address every single change, but these comments apply to multiple changes:
I agree we should to use "dnGrep" everywhere.
I agree we should use sentence-style capitalization ([reference](https://docs.microsoft.com/en-us/style-guide/capitalization)).  I have always used title-style capitalization in table headers, but that isn't correct ([reference](https://docs.microsoft.com/en-us/style-guide/scannable-content/tables)).
In general, I'm going to say no to all the added hyphens, I don't think this is correct usage ([reference](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens)).  However, there are be some specific exceptions where you are correct.
"Filename" should be two words: [reference](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/f/file-name).  Same for "File size" and "File type".
"Plaintext" should be two words: [reference](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/plaintext-plain-text).
"Multiline" is the correct spelling, not "Multi-line": [reference](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/m/multi)
I'm going to go with US spelling, so "canceled" not "cancelled" [reference](https://docs.microsoft.com/en-us/style-guide/word-choice/use-us-spelling-avoid-non-english-words). If someone wants to create an en-GB resource, they can used British spelling.

2021-12-04 21:14 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Bookmark details dialog, pattern type radio button label (accel)</comment>
It doesn't translate well. More often people will use something other than "Regex" if it is written in full.

2021-12-04 21:20 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Help dialog header text</comment>
Consistency
    <value>Hex string is not valid!</value>
    <value>The regular expression is not valid.</value>
    <value>XPath is not valid!</value>
    <value>The search path in the '{0}' field is not valid, search cancelled.</value>
    <value>The replacement text is not valid XML!</value>

2021-12-04 21:23 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, result options context lines tooltip</comment>
I got that part, but failed at "Context changes".

2021-12-04 21:25 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Everything index Service</value>
I think it may be "Everything service" https://www.voidtools.com/support/everything/everything_service/ but I am not concerned.

2021-12-04 21:30 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, file filters summary</comment>
That would be `By "Date created"` or `By "Date modified"`
It sounds like "By soil created, the plant needed only sun and water to blossom"

2021-12-04 21:32 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, main menu subitem label (accel)</comment>
"Help" is a string below this though. Which string is the top menu?

2021-12-04 21:34 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, search options, reset button label (accel)</comment>
"Reset options" could be ~"Settings for the reset option".

2021-12-04 21:35 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Match {0}{1}Group {2}: {3}</value>
Can you provide a screenshot?

2021-12-04 21:36 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, status bar message</comment>
Does it mean "replaced the cancelled ___ (elements?)" or "The action of replacing was cancelled"?

2021-12-04 21:37 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, status bar message</comment>
Replace the failed something, or failed to replace?
These really add up when trying to translate this.

2021-12-04 21:38 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Test the expression</value>
Just trying to avioid "This is a test expression" in translation

2021-12-04 22:07 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Match {0}{1}Group {2}: {3}</value>
![image](https://user-images.githubusercontent.com/17227248/144726023-a71061b6-0364-4409-99fa-596438cbc71c.png)

2021-12-04 22:12 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Replace search-pattern with empty string?</value>
The "Are you sure" is falling out of fashion, and it can't happen soon enough.

2021-12-04 22:19 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Could not perform replacement. See the error log for details: </value>
The original could mean "Replace the failed ___!"
Your suggestion is much better, because then the user and translator knows what is going on.

2021-12-04 22:24 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Run dnGrep as administrator to change showing dnGrep in the file-manager right-click menu</value>
That would be "Administrator" I think.
I also think you misread that, since it says "To log on as an administrator, you need to have a user account", that has to be the Windows-admin.(?)

Doesn't it open the file-intent media type? If the user installs a different file-manager (I think midnight commander is available) and select it as the default in Windows, won't it open in that?

2021-12-04 22:26 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Could not carry out search. See the error log for details: </value>
Idem. Went with yours even if it could imply the search got started.

2021-12-04 22:32 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <comment>Options dialog, resulting options context label</comment>
Then I have no idea what this means.
It is a noun-bingo :)

2021-12-04 22:40 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Detect file-encoding when only searching for filename pattern</value>
It bothers me that what you are saying is correct.

2021-12-04 22:46 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Show resulting lines in context</value>
Could this be explained?

2021-12-04 22:47 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Run dnGrep as administrator to replace all of them.</value>
My change doesn't make sense to me… :)

2021-12-04 22:54 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <comment>Replace window, filename progress line: {0} is the index of the current file; {1} is the total number of files; {2} is the name of the current file; {3} is the number of matches found in
It is a trade-off between one and the other. Maybe a better solution could be found? Em dash?

2021-12-04 23:01 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Exclusion pattern:</value>
Can't find "Patterns excluded"

2021-12-04 23:05 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Using \"Everything index\" search</value>
Agreed. It is fine when it is in quotes.
One of them is "Everything" search tool, which makes it clear

2021-12-04 23:06 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Restore Downwards</value>
I don't have any Windows. Would add a screenshot on Weblate for this.

2021-12-04 23:09 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>About</value>
This is the more common one, and the other is mostly used when there is a "About Qt" without a nested menu.

2021-12-04 23:17 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>    </resheader>
I failed to remember most of these on the second go just now.

Don't trust Windows anything, especially their language guide. https://en.wikipedia.org/wiki/Filename
"Plaintext" means "in clear text", which is mostly for transfers. Probably wrong.

However, there are too many "Plugin failed to load error" type disasters for me to think of those as actual problems yet.

The English/non-English spelling issue is best solved by having this as the base file, and then both "en_UK" and "en_US" as translatable resources with the "clear empty strings"(?) plugin in Weblate.

Sentence casing is the biggest issue of those. What is the current situation there?

2021-12-05 00:06 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Bookmark details dialog, pattern type radio button label (accel)</comment>
My preference is mostly that it is shorter and doesn't take up as much space on the screen.  I guess "Hex" needs to be changed to "Hexadecimal" too.

2021-12-05 00:10 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>About</value>
This is the title on the dialog box, not the menu text.  But either way works for the dialog title.

2021-12-05 00:17 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, file filters summary</comment>
Fine, then use `By created date`, which parallels `By modified date`.

2021-12-05 00:24 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, main menu subitem label (accel)</comment>
Here is the current version:
<img src="https://user-images.githubusercontent.com/17227248/144728728-6b2fae33-499f-4491-9776-7fe44c0540a8.png" width="200"/>

Here is what you changed it to:
<img src="https://user-images.githubusercontent.com/17227248/144728763-ba543ebd-fb01-4a1e-82d2-4328e94cae69.png" width="180"/>

I was suggesting it would be better to have the top-level menu "Help" and sub-menus "View Help" and "About".

2021-12-05 00:28 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, search options, reset button label (accel)</comment>
This is the label on a button, it should read in the form of an action.  I think "Reset filters" is the best choice.
<img src="https://user-images.githubusercontent.com/17227248/144728836-ae3cbc00-cb72-4829-81c9-1692d91c5dd3.png" width="400"/>

2021-12-05 00:31 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, status bar message</comment>
The second: the action of replacing text in files was canceled.    It is the text shown on the main window status bar after the user clicks the Cancel button during a replace operation.

2021-12-05 00:33 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, status bar message</comment>
The second, failed to replace.  This is shown on the main window status bar at the conclusion of the replace operation, if the operation ended in a failure.

2021-12-05 00:35 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Test the expression</value>
This is a button text.  It should read in the form of a command, not an explanation. 
<img src="https://user-images.githubusercontent.com/17227248/144728934-69f2f212-d3a3-460a-a3db-2473b5ebc1d7.png" width="240"/>

2021-12-05 00:57 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Show resulting tree expanded</value>
"Results tree" is a compound noun - it is the area where the search results are shown.  This setting indicates if the user wants the tree to be fully expanded as results are added to the tree (which is slower and more memory intensive, especially for large files).

2021-12-05 01:04 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <comment>Replace window, filename progress line: {0} is the index of the current file; {1} is the total number of files; {2} is the name of the current file; {3} is the number of matches found in
If using an Em dash, then the parentheses should be removed.  Or, could use a Em Quad space.

2021-12-05 01:10 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Restore Downwards</value>
Here is an example from Notepad++, but it could be any Windows application.

<img src="https://user-images.githubusercontent.com/17227248/144729448-d271615b-c49a-4118-af22-e0b85bd4c06c.png" width="180"/>

2021-12-05 01:14 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Replace search-pattern with empty string?</value>
I just think it's not clear as changed.  Maybe "The search pattern will be replaced with an empty string.  Continue?"

2021-12-05 01:20 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Run dnGrep as administrator to change showing dnGrep in the file-manager right-click menu</value>
The way dnGrep is shown in the Windows Explorer right-click menu is by keys and values to the Windows Registry.  It is not the same as registering an application for a file type. I don't know how other file mangers work - do they make use of the same Registry keys?  All I am supporting is Windows Explorer, if someone wants to use something else, it may or may not work.

2021-12-05 01:25 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <comment>Options dialog, resulting options context label</comment>
Here it is in the Options dialog.  I'm not sure how to describe it.

<img src="https://user-images.githubusercontent.com/17227248/144729710-f82c7224-0d69-4ea6-a9eb-3681c2779fb3.png" width="600"/>

2021-12-05 01:31 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Detect file-encoding when only searching for filename pattern</value>
dnGrep has a possibly obscure feature that allows you search with an empty "Search for" pattern.  In this mode, dnGrep will generate a list of files using all of the file filters, but not searching within the file.  It would be great to have a better way of naming this feature.  Setting this option tells dnGrep to also run the file encoding check when listing files, which isn't necessary to simply list the files.

2021-12-05 01:37 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Show resulting lines in context</value>
You may be correct.  But I think at least in the US, that form of 'result' is not normally used.  The search produces result lines (the line where a match is found), which may or may not also include context lines.

2021-12-05 01:39 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Run dnGrep as administrator to replace all of them.</value>
Maybe: "You must run dnGrep under an Administrator account to change this setting."

2021-12-05 01:48 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Restore Downwards</value>
I didn't realize that dnGrep would run on any operating system other than Windows.  Or you aren't a dnGrep user??

2021-12-05 04:17 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Match {0}{1}Group {2}: {3}</value>
That looks off to me.  Noticed the "  brown" right away, so I was looking for something subtle and then read the comment to find it was that. Could be just me being sensitive to it though.
Was thinking something like 
![bilde](https://user-images.githubusercontent.com/13802408/144733148-313912c7-98fd-44b4-b1aa-0c419ad297de.png)
![bilde](https://user-images.githubusercontent.com/13802408/144733167-b86c9077-bcc2-46d9-add5-1fe9ef633c51.png)
![bilde](https://user-images.githubusercontent.com/13802408/144733181-7751511f-5880-4bce-8283-72a3c2dba6d0.png)

2021-12-05 04:33 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, search options, reset button label (accel)</comment>
Is "Reset Selections" possible?

2021-12-05 04:40 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, main menu subitem label (accel)</comment>
I understand. I am thinking "Help" for the top cateogry is better.
I strongly prefer both "Help" and "About" available directly, with no nested menus.
What is available in "Help"?

2021-12-05 04:41 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>By modified date</value>
```suggestion
    <value>By modification date</value>
```

2021-12-05 04:43 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, file filters summary</comment>
Can I change that to "By modification date" below?
Changed more similar ones in https://github.com/dnGrep/dnGrep/pull/593/files#r762461930 already.

2021-12-05 04:45 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Changes the number of shown context lines for new searches.</value>
```suggestion
    <value>Changes the number of shown context lines for new searches</value>
```

2021-12-05 04:49 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, main menu subitem label (accel)</comment>
Haven't you ever run the application?  Maybe that's why this is so difficult.  The help button takes you a set of [wiki pages](https://github.com/dnGrep/dnGrep/wiki) on github.  Which I'm now going to have to redo to change all the images and text references.

2021-12-05 04:53 UTC, doug24 commented on dnGREP.Localization/Properties/Resources.resx
>      <comment>Main window, file filters summary</comment>
But why change them at all?   "Created" and "Modified" are the usual nomenclature, at least in US English Windows.  
<img src="https://user-images.githubusercontent.com/17227248/144734159-24f0ad26-b119-49f0-aded-00db013702d6.png" width="400"/>

2021-12-05 04:54 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Test the expression</value>
```suggestion
    <value>Test Expression</value>
```

2021-12-05 05:18 UTC, comradekingu commented on dnGREP.Localization/Properties/Resources.resx
> +    <value>Restore Downwards</value>
Possibly it could run in mono or Wine, but my interest is just in helping.

2021-12-05 08:01 UTC, doug24 commented
Allan, I am astounded that you would put this much time and effort into an application that you have never seen and will never use.  It would have been nice if you had been up front about not knowing the application.  I would not have guessed that someone would try to translate it without ever having used it.  How did you even hear of this application? I have a guess...  

I do appreciate the contributions.  The application gets better when more people contribute, report bugs and suggest enhancements.  This application has a small but loyal following.  Personally, I don't care how many people use it as long as there are some who do like it and find it useful. They tell me they do. I maintain dnGrep on my own time, and no one compensates me for it.  I like the application, and this is my way of contributing to the open source community.

Over the years there have been a few, but not many, requests to change or clarify the text.  Yes, there is room to improve the clarity and make it more consistent. But you want to change *everything*.  I don't think the existing users of the application want everything to change. 

I have your commits, and we've had a lot of discussion on what should be changed.  I think at this point the best way forward is if I make the changes and create another PR.  It would be good if others also commented on the changes, but I understand it is really difficult to review these changes on github without being able to see them live in the application.

2021-12-08 06:05 UTC, comradekingu commented
@doug24 How much I want to change is not a product of my desire for change.
What is present in this PR is not even all of the strings with similar problems, which you seem sympathetic to.
Whatever happened here in the course of time goes to show something needed to be done.
Yes I could have been the perfect linguist, or had all the time in the world, etc.
Not knowing the app means I only decipher strings based on what is conveyed in them, at best. I take that into account.
In some sense this is a strength, although it does require you to use a bit more time to clue me in when context is needed.
Blind users don't have a whole lot more to go by, and there is no reason that couldn't be a good use-case.
People translating the app will only have the screenshots to go by, or not even that, so we should not leave the perfect understanding of each string down to how much of your special knowledge is at hand.

There is no reason this should be a specialty project. It has a lot of generic utility, but things like this is what keeps it
exclusive to a select audience.

I have done this sort of thing in some 500+ projects now.
Of all the projects I have ever seen or translated in total, the current dnGrep stringbase ranks toward the ultimate bottom for clarity.
That is a challenge, and that is how I can improve in what I do, even if people don't really understand or do it all that often.
The sooner you stop pushing inertia onto users for supposed unwillingness to have change, the sooner it can be done right.
That means more users, and a more welcoming program.
If you want me to help set up a donation effort for you, I can do that too.
The only reason I wouldn't be working with you is if you don't want to, but so far it has been a pleasure.

If we can get this merged, it makes it a lot easier for me to know what got done and what needs doing. I have a plan.
If you decide to pick and choose, you are trusting your ability to know all the considerations I put into this.
I don't have it in me to go down that road.

2021-12-08 20:18 UTC, doug24 commented
I am not a translator or a linguist. I never imagined that translations would be done by people who have never run the application and don't know how it works.  I never imagined someone could make a usable translation from a screenshot.  I remain unconvinced that this is gong to work.  

I just don't see how you can change the text without understanding what you are changing. And if you don't run the application, you can't see what changes your are making. I think you would make different choices if you could see what you have done.

There are too many problems with this PR to merge it, and I don't have time to discuss every last string with you. 

I just raised a PR where I started with your changes, and attempted to fix issues in it.  If you are issuing an ultimatum that you have full control or you are going leave, then so be it.  I'm sorry the application is so "grim" and that you had to work on it.

2021-12-09 01:03 UTC, doug24 commented
PR #594 
So tell me what you hate, and what you can't live with.  I know it's going to be difficult without knowing how or why the string is used in the application - but they have to make sense in the context of what is happening in the application.  If you aren't able to find a way to run the application, I'm not sure how I can help you.   

Once this is merged, I can start creating new screen captures.  Ideally, how much of the screen should be included in each capture?  Obviously more than a single field on the screen.  Some strings appear conditionally, so there will need to be multiple screen captures of some parts of the application.  This is going to take time, and I don't have a lot of extra time right now - I did have other plans for last weekend that I never got to after spending so much time responding to you.

I'm still very skeptical that an army of translators will appear that have never run, and will never run the application (why would they invest the time?).   You seem to think they will be able to do it off just the screen captures.  OK, that works for me, as I'm not going to take the time to walk each of them through the application.

2021-12-11 23:37 UTC, closed without merging