Rearrange the buttons / checkbox
dnGrep/dnGrep pull request #681
Opened 2022-06-07 16:11 UTC by Yahasana

![image](https://user-images.githubusercontent.com/97450/172429934-2de44377-1c1c-46b1-a333-a2bd68454c58.png)

2022-06-08 00:50 UTC, doug24 requested changes
I like this layout but have a few requests shown below.  Also, I think the tab ordering can be improved - I try to put them in visual order, but with some of the moves the tab order jumps around.

2022-06-08 00:50 UTC, doug24 commented on dnGREP.WPF/Views/MainView.xaml
> +                             TabIndex="94" Height="20">
You cannot set a fixed height on TextBoxes, if the user changes the font size, then the text will get clipped.

2022-06-08 00:50 UTC, doug24 commented on dnGREP.WPF/Views/MainView.xaml
> +                             TabIndex="95" Height="20">
You cannot set a fixed height on TextBoxes, if the user changes the font size, then the text will get clipped.

2022-06-08 00:50 UTC, doug24 commented on dnGREP.WPF/Views/MainView.xaml
> +                                            <ColumnDefinition Width="Auto" />
Not clear why the grid was increased to 4 columns, none of the child rows use 4 columns.

2022-06-08 00:50 UTC, doug24 commented on dnGREP.WPF/Views/MainView.xaml
> +                                            <Button Margin="0,0,3,3"  Padding="8,3" HorizontalAlignment="Right"
I think it would be better if this button was not on the same row as the encoding - it makes the right panel much wider than it needs to be.

2022-06-08 16:10 UTC, Yahasana commented on dnGREP.WPF/Views/MainView.xaml
> +                                            <ColumnDefinition Width="Auto" />
when show search option in expender is on, these options occupy two columns. 4 columns make the above options with good alignment

2022-06-09 00:29 UTC, doug24 commented on dnGREP.WPF/Views/MainView.xaml
> +                                            <ColumnDefinition Width="Auto" />
Here's what I see:
The outer red box is a grid with 6 rows and 4 columns (named "RightFileOptions")
The yellow box is a stack panel in grid row 0 and column span of 4
Search parallel is in grid row 1 with column span of 2
Use .gitignore is in grid row 1 with column span of 2
Skip remote cloud storage files is in grid row 2 with a column span of 4
The blue box is stack panel in grid row 3 with a column span of 4
The green box is a grid in the outer grid row 4 with a column span of 4 (this grid has 4 rows and 2 columns)
So only 'Search Parallel' and 'Use .gitignore' are using 2 columns in the outer grid, all the other rows span all of the columns

<img src="https://user-images.githubusercontent.com/17227248/172739054-29e3738d-c935-48e3-a5a9-3507059bd173.png" width="680"/>

2022-06-12 03:11 UTC, Yahasana commented on dnGREP.WPF/Views/MainView.xaml
> +                                            <Button Margin="0,0,3,3"  Padding="8,3" HorizontalAlignment="Right"
I move the popup window to statusbar, but there is still a bug. it'd be hidden when the popup window show. any suggestion is welcome 
![image](https://user-images.githubusercontent.com/97450/173212534-8a854b6b-c5b2-4af4-a15a-c978b5cbae33.png)

2022-06-12 04:01 UTC, doug24 commented on dnGREP.WPF/Views/MainView.xaml
> +                                            <Button Margin="0,0,3,3"  Padding="8,3" HorizontalAlignment="Right"
Why move it?  The other window control buttons are at the top - why put this one at the bottom?

2022-06-12 04:01 UTC, doug24 commented
What is your goal here? What are you trying to do?

2022-06-12 07:07 UTC, Yahasana commented on dnGREP.WPF/Views/MainView.xaml
> +                                            <Button Margin="0,0,3,3"  Padding="8,3" HorizontalAlignment="Right"
this preview pop out button is close next to the close button. look not good and may miss click the close button

2022-06-12 07:08 UTC, Yahasana commented
> What is your goal here? What are you trying to do?

may the UI clean and clear

2022-06-12 16:51 UTC, doug24 commented
In the existing code, the dock site is a windowing control that switches between docked in a window or floating in its own window.  It supports both docking and undocking and you can use any control in the content area.  The preview window is a content control that can be put in any parent content control.
With your modifications, the dock site no longer has a way to undock the control, that responsibility has been moved to the child content.  And the preview control now has additional code to support undocking, making it so it can only be used in a docking window.
Also, I think the new location is confusing. I don't like mixing responsibilities like this, so this change is a 'no' for me.

2022-06-14 13:31 UTC, fade2gray commented
> this preview pop out button is close next to the close button. look not good and may miss click the close button

I can see the concern in misclicking the close button when aiming for the preview panel dock button, in fact, it's something I'm very likely to do. I suffer with Rheumatoid Arthritis and my hand movements can be a little erratic at times. ¯\\_(ツ)_/¯¯

2022-06-20 23:51 UTC, doug24 commented
I don't like reviewing pull requests which largely come down to personal preferences.  It is difficult to change the layout of an app, and the previous two times we made substantial changes there was a lot of discussion around them to arrive at where it is now. I end up having to maintain this, and I'm very reluctant to make changes to the layout.  The only thing I can do is tell you my objections and try to explain why I don't want to merge all these changes.


1. Moving the Reset Filters button here makes this group of controls needlessly wide.  I think this area has more a of width constraint than a height constraint.  But then, I usually have the search options on the main window, not in the expander panel (that layout option was a compromise in earlier changes).

<img src="https://user-images.githubusercontent.com/17227248/174684786-b13a8f67-b53a-4956-ac3c-12531056538a.png" width="400"/>

2. Is it common for users to change the zoom level of the Results Tree?  I don't think so, and it's not clear why it should be moved to such a prominent position in the middle of the screen.  I think it belongs in the collapsible panel below the results tree, and that way both zoom controls are below the window they modify.  The collection of the controls below the results tree modify the layout or format of the results.

<img src="https://user-images.githubusercontent.com/17227248/174687452-30e92902-2bdb-4f75-9f4d-7efd11559d37.png" width="400"/>

3. On the Preview Window "Zoom" control, you changed the maximum value to 100.  Because the edit control doesn't support zooming, this control is changing the font size of the edit control.  Font side 100 is way too big, which is why the previous upper limit is 30.  

4. I see you changed the code for the pop-out button, but you didn't address either of my concerns:  The docking behavior is still removed from the docking control and put into the child control.  That breaks the separation of responsibility in the controls.  Second, I think the window controls should together and not split to different locations - why make it harder to find?  My preference is to keep it where it currently is, but if it is really a problem being close to the Close button, why not just move it to the near side or add a bit of space?

<img src="https://user-images.githubusercontent.com/17227248/174685895-5ca38448-4074-494a-a4c4-ee8f00d7e445.png" width="400"/>

5. I don't understand why you would cut off the top of the splitter bar, but I guess it's just preference. 
 
<img src="https://user-images.githubusercontent.com/17227248/174689238-8766a089-b897-4272-ada0-7307c06262d3.png" width="280"/>

6. I didn't look to see where it got broken, but when the Preview window is docked to the bottom of the main window, the splitter bar has been lost.  Compare the original first to your change second:

<img src="https://user-images.githubusercontent.com/17227248/174686233-e6441eaa-5346-4a97-a312-b05131593d29.png" width="400"/>

<img src="https://user-images.githubusercontent.com/17227248/174686244-949d6bb9-527d-4242-a183-cf68909769fa.png" width="400"/>

7. The Regex label - yes that is the way it was until about 6 or 9 months ago when I had another pull request to change many of the strings in dnGrep.  After a lot of discussion and back and forth, I accepted many of the changes including this one.  I think this largely comes down to preferences and I don't want to just change it again.

2022-06-21 13:14 UTC, Yahasana commented
Thanks for the reviews.

The first and most preference I like:

1) make the `search results` area as big as it can.
   a) `Regular expression` may lead to line break when making the panel smaller. so rename it to `Regex`
   b) `Results zoom slider` may lead to  line break when making the panel smaller. so move it up to the top (enough free space for it). I don't like it occupy the most important place too
   c) The same reason for `Preview checkbox`, good for me.
   e) The same reason for `Stop after first match`. It's my first time to play with `wpf`. I break something but seem works

2)  make the preview area as big as it can.
   rearrange the options in the bottom of the preview control to avoid line break happen when the panel zoom in smaller.

Two more things
I don't like any other icon show very close to minimize / maximize / close buttons (anti-convention). 
adding some padding space will break the rule above. so the right bottom corner is it right place to go. 
(when i turn my eye to right bottom corner of this comment editor, there is an icon there too.)

I like round corner and work hard to cut the split bar to make it look like a round one, 
and make its background color look like a soft border.
(I did find it's not so perfect in dark mode and don't fix it as I seldom use dark mode. sorry)

2022-07-23 18:45 UTC, closed without merging